### ISSUE TITLE
ERROR -Altay3.0.6

### ISSUE THREAD

**Issue by raidksh** [Hyroxing/LobbyParticle-AddON#2]
CRITICAL > Error: "Call to undefined method iTzFreeHD\PC\Particle::scheduleRepeatingTask()" (EXCEPTION) in "Particle - iTzFreeHD/src/iTzFreeHD/PC/ParticleTask" at line 18
00:49:53 DEBUG > #0 Particle - iTzFreeHD/src/iTzFreeHD/PC/Particle(35): iTzFreeHD\PC\ParticleTask->__construct(iTzFreeHD\PC\Particle object)
00:49:53 DEBUG > #1 src/pocketmine/plugin/PluginBase(111): iTzFreeHD\PC\Particle->onEnable()
00:49:53 DEBUG > #2 src/pocketmine/plugin/PluginManager(615): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
00:49:53 DEBUG > #3 src/pocketmine/Server(2043): pocketmine\plugin\PluginManager->enablePlugin(iTzFreeHD\PC\Particle object)
00:49:53 DEBUG > #4 src/pocketmine/Server(2029): pocketmine\Server->enablePlugin(iTzFreeHD\PC\Particle object)
00:49:53 DEBUG > #5 src/pocketmine/Server(1792): pocketmine\Server->enablePlugins(integer 1)
00:49:53 DEBUG > #6 src/pocketmine/PocketMine(241): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\ghkst\Desktop\Altay-master\, string C:\Users\ghkst\Desktop\Altay-master\plugins\)
00:49:53 DEBUG > #7 C:/Users/ghkst/Desktop/Altay-master/Altay.phar(1): require_once(string phar://C:/Users/ghkst/Desktop/Altay-master/Altay.phar/src/pocketmine/PocketMine.php)

**Comment by iTzFreeHD** [comment]
Thanks for reporting the Error

**Comment by Hyroxing-Development** [comment]
The Error has been Fixed :D
